[package]
name = "arcella-core"
version = "0.1.0"
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Modular, secure WebAssembly platform for building component-based applications"
keywords = ["wasm", "webassembly", "runtime", "modular", "component-model"]
categories = ["wasm", "development-tools", "embedded"]

[dependencies]
arcella-types = { path = "../arcella-types" }
ministate = { workspace = true }
derive_builder = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
wasmtime = { workspace = true }
uuid = { workspace = true }
wat = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
