# arcella/arcella-types/Cargo.toml
[package]
name = "arcella-types"
version = "0.1.1"
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core data types and manifests for the Arcella WebAssembly runtime"
keywords = ["wasm", "webassembly", "component-model", "manifest", "types"]
categories = ["wasm", "development-tools"]

[dependencies]
flexicon = { workspace = true, features = ["serde"] }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
ordered-float = { workspace = true }

[dev-dependencies]
toml = "0.9.8"

[lints]
workspace = true
